// desktop-web-app/web-app/src/components/editable-input.tsx
/*
 *  Copyright (c) 2025 TeamDev
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import {Input} from "@/components/ui/input.tsx";
import {ChangeEventHandler, useState} from "react";

/**
 * The input's properties.
 */
interface InputProps {
    title: string,
    value: string,
    id: string,
    isEmail: boolean,
    onChange: (value: string) => void
}

/**
 * An input field with the user's data.
 *
 * @param title the input's title
 * @param value the input's value
 * @param isEmail indicates if the input contains an email
 * @param onChange a callback that is invoked when the input's value has been changed,
 * specifically on blur
 * @constructor
 */
export function EditableInput({title, value, isEmail, onChange}: InputProps) {
    const [isValid, setIsValid] = useState(true);

    const handleInputChange: ChangeEventHandler<HTMLInputElement> = (e) => {
        const value = e.target.value;
        if (isEmail) {
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            const isValid = emailRegex.test(value);
            setIsValid(isValid);
        }
    };
    return (
        <div className="w-full items-center space-y-2">
            <div className="w-full sm:flex items-center space-y-1 justify-between">
                <p className="text-sm">{title}</p>
                <div className={"xs:w-full sm:w-[50%] lg:w-[30%]"}>
                    <Input type={isEmail ? "email" : "text"}
                           className={`w-full text-sm ${!isValid && "bg-red-300"}`}
                           onBlur={(event) => {
                               if (isValid) {
                                   onChange(event.target.value);
                               } else {
                                   event.target.value = value;
                                   setIsValid(true);
                               }
                           }}
                           onChange={handleInputChange}
                           defaultValue={value}/>
                    {!isValid && (
                        <span className="text-xs text-red-500">
                            Please enter a valid email address.
                        </span>
                    )}
                </div>
            </div>
        </div>
    );
}

// desktop-web-app/web-app-vue/src/components/account/EditableInput.vue
<!--
  Copyright 2026, TeamDev

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
-->

<script setup lang="ts">
import {computed, ref, watch} from 'vue'
import Input from '@/components/ui/Input.vue'

interface Props {
  title: string
  modelValue: string
  isEmail?: boolean
}

const props = defineProps<Props>()
const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()

const localValue = ref(props.modelValue)
const isValid = ref(true)

watch(
  () => props.modelValue,
  (val) => {
    localValue.value = val
  }
)

const inputType = computed(() => (props.isEmail ? 'email' : 'text'))

const inputClasses = computed(() => {
  return [
    'w-full text-sm focus-visible:border-control-select transition-colors',
    !isValid.value ? 'bg-red-300 focus-visible:border-red-500' : '',
  ]
})

watch(localValue, (val) => {
  if (props.isEmail) {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    isValid.value = emailRegex.test(val)
  }
})

function handleBlur() {
  if (!isValid.value) {
    localValue.value = props.modelValue
    isValid.value = true
    return
  }
  emit('update:modelValue', localValue.value)
}
</script>

<template>
  <div class="w-full items-center space-y-2">
    <div class="w-full sm:flex items-center space-y-1 justify-between">
      <p class="text-sm">{{ title }}</p>
      <div class="xs:w-full sm:w-[50%] lg:w-[30%]">
        <Input
          v-model="localValue"
          :type="inputType"
          :class="inputClasses.join(' ')"
          @blur="handleBlur"
        />
        <span v-if="!isValid" class="text-xs text-red-500">
          Please enter a valid email address.
        </span>
      </div>
    </div>
  </div>
</template>
