// desktop-web-app/web-app/shadcn/src/components/sidebar.tsx
/*
 *  Copyright (c) 2024 TeamDev
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import {
    Sidebar,
    SidebarContent,
    SidebarGroup,
    SidebarGroupContent,
    SidebarGroupLabel,
    SidebarMenu,
    SidebarProvider,
    SidebarTrigger
} from "@/components/ui/sidebar.tsx";
import {Bell, Settings, SquareUser, SunMoon} from "lucide-react";
import {NavigationItem} from "@/components/navigation-item.tsx";
import {Account} from "@/components/account.tsx";
import {Route, Routes} from "react-router-dom";
import {Appearance} from "@/components/appearance.tsx";
import {General} from "@/components/general.tsx";
import {Notifications} from "@/components/notifications.tsx";

export function LeftSidebar() {
    return (
        <SidebarProvider className="space-y-4 space-x-4 ">
            <Sidebar side="left" className="space-y-8 space-x-6 " collapsible="offcanvas">
                <SidebarContent className="p-4">
                    <SidebarGroup/>
                    <SidebarGroupContent>
                        <SidebarMenu>
                            <NavigationItem title={"Account"} url={"/"} icon={SquareUser}/>
                        </SidebarMenu>
                    </SidebarGroupContent>
                    <SidebarGroupLabel>Preferences</SidebarGroupLabel>
                    <SidebarGroupContent>
                        <SidebarMenu>
                            <NavigationItem title={"General"} url={"/prefs/general"}
                                            icon={Settings}/>
                            <NavigationItem title={"Appearance"} url={"/prefs/appearance"}
                                            icon={SunMoon}/>
                            <NavigationItem title={"Notifications"} url={"/prefs/notifications"}
                                            icon={Bell}/>
                        </SidebarMenu>
                    </SidebarGroupContent>
                    <SidebarGroup/>
                </SidebarContent>
            </Sidebar>
            <main className="w-full">
                <SidebarTrigger/>
                <div className=" w-full px-20 py-10 sm:w-3/4 md:w-1/2 lg:w-3/4">
                    <Routes>
                        <Route path={"/"} element={<Account/>}/>
                        <Route path={"/prefs/general"} element={<General/>}/>
                        <Route path={"/prefs/appearance"} element={<Appearance/>}/>
                        <Route path={"/prefs/notifications"} element={<Notifications/>}/>
                    </Routes>
                </div>
            </main>
        </SidebarProvider>
    )
}

// desktop-angular-dashboard/web-app/src/app/components/layout/sidebar.component.ts
/*
 * Copyright 2026, TeamDev
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NgIconComponent, provideIcons } from '@ng-icons/core';
import { 
  lucideLayoutDashboard, 
  lucideChartLine, 
  lucideUsers, 
  lucideFolderKanban,
  lucideSettings,
  lucideSearch,
  lucideCircleHelp,
  lucideChevronDown,
  lucideDatabase,
  lucideFileText,
  lucidePenTool
} from '@ng-icons/lucide';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, NgIconComponent],
  viewProviders: [provideIcons({ 
    lucideLayoutDashboard, 
    lucideChartLine, 
    lucideUsers, 
    lucideFolderKanban,
    lucideSettings,
    lucideSearch,
    lucideCircleHelp,
    lucideChevronDown,
    lucideDatabase,
    lucideFileText,
    lucidePenTool
  })],
  template: `
    <div class="flex h-screen w-64 flex-col border-r border-border bg-card">
      <!-- Logo -->
      <div class="flex h-14 items-center border-b border-border px-4">
        <div class="flex items-center gap-2">
          <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
            <span class="text-sm font-bold">JX</span>
          </div>
          <span class="font-semibold text-foreground">JxBrowser</span>
        </div>
      </div>

      <!-- Navigation -->
      <div class="flex-1 overflow-y-auto py-4">
        <!-- Home Section -->
        <div class="px-3 py-2">
          <h2 class="mb-2 px-2 text-xs font-semibold tracking-tight text-muted-foreground">
            Home
          </h2>
          <div class="space-y-1">
            <a class="flex items-center gap-3 rounded-lg bg-accent px-3 py-2 text-accent-foreground transition-colors">
              <ng-icon name="lucideLayoutDashboard" class="h-4 w-4" />
              <span class="text-sm">Dashboard</span>
            </a>
            <a class="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors cursor-pointer">
              <ng-icon name="lucideChartLine" class="h-4 w-4" />
              <span class="text-sm">Analytics</span>
            </a>
            <a class="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors cursor-pointer">
              <ng-icon name="lucideFolderKanban" class="h-4 w-4" />
              <span class="text-sm">Projects</span>
            </a>
            <a class="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors cursor-pointer">
              <ng-icon name="lucideUsers" class="h-4 w-4" />
              <span class="text-sm">Team</span>
            </a>
          </div>
        </div>

        <!-- Documents Section -->
        <div class="px-3 py-2">
          <h2 class="mb-2 px-2 text-xs font-semibold tracking-tight text-muted-foreground">
            Documents
          </h2>
          <div class="space-y-1">
            <a class="flex items-center justify-between rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors cursor-pointer">
              <div class="flex items-center gap-3">
                <ng-icon name="lucideDatabase" class="h-4 w-4" />
                <span class="text-sm">Data Library</span>
              </div>
              <ng-icon name="lucideChevronDown" class="h-4 w-4" />
            </a>
            <a class="flex items-center justify-between rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors cursor-pointer">
              <div class="flex items-center gap-3">
                <ng-icon name="lucideFileText" class="h-4 w-4" />
                <span class="text-sm">Reports</span>
              </div>
              <ng-icon name="lucideChevronDown" class="h-4 w-4" />
            </a>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="border-t border-border p-3">
        <div class="space-y-1">
          <a class="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors cursor-pointer">
            <ng-icon name="lucideSettings" class="h-4 w-4" />
            <span class="text-sm">Settings</span>
          </a>
          <a class="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground hover:bg-accent hover:text-accent-foreground transition-colors cursor-pointer">
            <ng-icon name="lucideCircleHelp" class="h-4 w-4" />
            <span class="text-sm">Get Help</span>
          </a>
        </div>
      </div>
    </div>
  `
})
export class SidebarComponent {}
