// desktop-web-app-vue/web-app/src/components/appearance/ThemeProvider.vue
<script setup lang="ts">
import { ref, provide, onMounted, watch } from "vue";
import { prefsStorage } from "@/storage/prefs-storage.ts";
import { systemTheme, ThemeOption, fromTheme } from "@/converter/theme.ts";
import {ThemeContext, ThemeContextKey} from "@/utils/theme-context.ts";
import {prefsClient} from "../../../rpc/prefs-client.ts";

const theme = ref<ThemeOption>(prefsStorage.theme() ?? systemTheme);

function setTheme(newTheme: ThemeOption) {
  prefsStorage.saveTheme(newTheme);
  theme.value = newTheme;
}

onMounted(async () => {
  try {
    const appearance = await prefsClient.getAppearance({});
    const loadedTheme = fromTheme(appearance.theme);
    setTheme(loadedTheme);
  } catch (e) {
    console.error("Failed to load theme:", e);
  }
});

watch(theme, (val) => {
  const root = document.documentElement;
  root.classList.remove("light", "dark");
  if (val === "system") {
    root.classList.add(
        window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light"
    );
  } else {
    root.classList.add(val);
  }
}, { immediate: true });

provide<ThemeContext>(ThemeContextKey, { theme, setTheme });
</script>

<template>
  <slot />
</template>

// desktop-web-app/web-app/shadcn/src/components/theme-provider.tsx
import React, {createContext, useContext, useEffect, useState} from "react"
import {getAppearance} from "@/rpc/app-preferences-service.ts";
import {fromTheme, systemTheme, ThemeOption} from "@/components/converter/theme.ts";
import {saveThemeInStorage, themeFromStorage} from "@/storage/appearance.ts";

type ThemeProviderProps = {
    children: React.ReactNode
    defaultTheme?: ThemeOption
    storageKey?: string
}

type ThemeProviderState = {
    theme: ThemeOption
    setTheme: (theme: ThemeOption) => void
}

const initialState: ThemeProviderState = {
    theme: systemTheme,
    setTheme: () => null,
}

const ThemeProviderContext = createContext<ThemeProviderState>(initialState)

export function ThemeProvider({
                                  children,
                                  ...props
                              }: ThemeProviderProps) {
    const [theme, setTheme] = useState<ThemeOption>(themeFromStorage());

    const setRootTheme = (theme: ThemeOption) => {
        const root = window.document.documentElement;
        root.classList.remove("light", "dark");
        if (theme === "system") {
            const systemTheme = window.matchMedia("(prefers-color-scheme: dark)")
                .matches
                ? "dark"
                : "light";

            root.classList.add(systemTheme);
            return;
        }
        root.classList.add(theme);
    }
    setRootTheme(theme);
    useEffect(() => {
        getAppearance(appearancePrefs => {
            const theme = fromTheme(appearancePrefs.theme);
            setTheme(theme);
            saveThemeInStorage(theme);
        });
    }, []);
    useEffect(() => setRootTheme(theme), [theme]);

    const value = {
        theme,
        setTheme: (theme: ThemeOption) => {
            saveThemeInStorage(theme);
            setTheme(theme);
        },
    }

    return (
        <ThemeProviderContext.Provider {...props} value={value}>
            {children}
        </ThemeProviderContext.Provider>
    );
}

export const useTheme = () => {
    const context = useContext(ThemeProviderContext);

    if (context === undefined)
        throw new Error("useTheme must be used within a ThemeProvider");

    return context;
}
