// desktop-web-app/web-app-vue/src/components/ui/Avatar.vue
<template>
  <div :class="['relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full', className]">
    <img
      v-if="showImage"
      :src="src"
      :alt="alt"
      :class="['aspect-square h-full w-full object-cover', imageClass]"
      @error="handleError"
    />
    <div
      v-else
      :class="[
        'flex h-full w-full items-center justify-center rounded-full bg-muted text-sm font-medium',
        fallbackClass,
      ]"
    >
      <slot>{{ fallback }}</slot>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, defineProps } from 'vue'

interface Props {
  className?: string
  src?: string
  alt?: string
  fallback?: string
  imageClass?: string
  fallbackClass?: string
}

const props = defineProps<Props>()

const showImage = ref(!!props.src)

watch(
  () => props.src,
  (newSrc) => {
    showImage.value = !!newSrc
  }
)

function handleError() {
  console.warn('Avatar image failed to load, showing fallback.')
  showImage.value = false
}
</script>

// desktop-web-app/web-app/src/components/ui/avatar.tsx
import * as React from "react"
import * as AvatarPrimitive from "@radix-ui/react-avatar"

import {cn} from "@/lib/utils.ts"

const Avatar = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Root>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Root>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Root
    ref={ref}
    className={cn(
      "relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full",
      className
    )}
    {...props}
  />
))
Avatar.displayName = AvatarPrimitive.Root.displayName

const AvatarImage = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Image>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Image>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Image
    ref={ref}
    className={cn("aspect-square h-full w-full", className)}
    {...props}
  />
))
AvatarImage.displayName = AvatarPrimitive.Image.displayName

const AvatarFallback = React.forwardRef<
  React.ElementRef<typeof AvatarPrimitive.Fallback>,
  React.ComponentPropsWithoutRef<typeof AvatarPrimitive.Fallback>
>(({ className, ...props }, ref) => (
  <AvatarPrimitive.Fallback
    ref={ref}
    className={cn(
      "flex h-full w-full items-center justify-center rounded-full bg-muted",
      className
    )}
    {...props}
  />
))
AvatarFallback.displayName = AvatarPrimitive.Fallback.displayName

export { Avatar, AvatarImage, AvatarFallback }
