// desktop-web-app/web-app-vue/src/components/account/UserAccount.vue
<!--
  Copyright (c) 2025 TeamDev

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
-->

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import Combobox from '@/components/ui/common/Combobox.vue'
import PreferenceSwitch from '@/components/ui/common/PreferenceSwitch.vue'
import EditableAvatar from '@/components/account/EditableAvatar.vue'
import EditableInput from '@/components/account/EditableInput.vue'
import GuidingLine from '@/components/ui/common/GuidingLine.vue'

import { AccountSchema, ProfilePictureSchema } from '@/gen/prefs_pb.ts'
import { create } from '@bufbuild/protobuf'
import { imageToDataUri } from '@/converter/image.ts'
import {
  emailTwoFA,
  smsTwoFA,
  passkeyTwoFA,
  fromTfa,
  toTfa,
  TwoFAMethod,
} from '@/converter/two-fa-method.ts'
import { prefsStorage } from '@/storage/prefs-storage.ts'
import { prefsClient } from '@shared/rpc/prefs-client'

const profilePictureDataUri = ref<string>('')
const fullName = ref<string>('')
const email = ref<string>('')
const twoFactorAuthentication = ref<TwoFAMethod>(prefsStorage.twoFA())
const biometricAuthentication = ref<boolean>(prefsStorage.biometricAuthenticationEnabled())

const initials = computed(() =>
  fullName.value
    .split(' ')
    .map((i) => i[0])
    .join('')
)

const authentications: TwoFAMethod[] = [emailTwoFA, smsTwoFA, passkeyTwoFA]

onMounted(async () => {
  try {
    const account = await prefsClient.getAccount({})
    email.value = account.email
    fullName.value = account.fullName

    const tfaMethod = fromTfa(account.twoFactorAuthentication)
    twoFactorAuthentication.value = tfaMethod
    biometricAuthentication.value = account.biometricAuthentication

    prefsStorage.saveTwoFA(tfaMethod)
    prefsStorage.saveBiometricAuthentication(account.biometricAuthentication)

    await loadProfilePicture()
  } catch (e) {
    console.error('getAccount failed:', e)
  }
})

async function loadProfilePicture() {
  try {
    const profilePicture = await prefsClient.getProfilePicture({})

    if (!profilePicture?.content || profilePicture.content.length === 0) {
      profilePictureDataUri.value = initials.value
      return
    }

    profilePictureDataUri.value = imageToDataUri(profilePicture.content)
  } catch (err) {
    profilePictureDataUri.value = initials.value
    console.error(err)
  }
}

function onUpdateAccount({
  newFullName = fullName.value,
  newEmail = email.value,
  newTwoFactorAuthentication = twoFactorAuthentication.value,
  newBiometricAuthentication = biometricAuthentication.value,
}: {
  newFullName?: string
  newEmail?: string
  newTwoFactorAuthentication?: TwoFAMethod
  newBiometricAuthentication?: boolean
}) {
  const newAccount = create(AccountSchema, {
    fullName: newFullName,
    email: newEmail,
    twoFactorAuthentication: toTfa(newTwoFactorAuthentication),
    biometricAuthentication: newBiometricAuthentication,
  })

  prefsClient.setAccount(newAccount)
  prefsStorage.saveTwoFA(newTwoFactorAuthentication)
  prefsStorage.saveBiometricAuthentication(newBiometricAuthentication)
}

function updateAccount({
  newFullName = fullName.value,
  newEmail = email.value,
  newTwoFactorAuthentication = twoFactorAuthentication.value,
  newBiometricAuthentication = biometricAuthentication.value,
}: {
  newFullName?: string
  newEmail?: string
  newTwoFactorAuthentication?: TwoFAMethod
  newBiometricAuthentication?: boolean
}) {
  const newAccount = create(AccountSchema, {
    fullName: newFullName,
    email: newEmail,
    twoFactorAuthentication: toTfa(newTwoFactorAuthentication),
    biometricAuthentication: newBiometricAuthentication,
  })

  prefsClient.setAccount(newAccount)
  prefsStorage.saveTwoFA(newTwoFactorAuthentication)
  prefsStorage.saveBiometricAuthentication(newBiometricAuthentication)
}

function updateBiometricAuthentication(checked: boolean) {
  biometricAuthentication.value = checked
  updateAccount({ newBiometricAuthentication: checked })
}

function onChangeAvatar(file: File) {
  const reader = new FileReader()
  reader.onload = () => {
    const newProfilePicture = create(ProfilePictureSchema, {
      content: new Uint8Array(reader.result as ArrayBuffer),
    })
    prefsClient.setProfilePicture(newProfilePicture)
    profilePictureDataUri.value = imageToDataUri(newProfilePicture.content)
  }
  reader.readAsArrayBuffer(file)
}
</script>

<template>
  <div class="space-y-4">
    <h1 class="text-2xl font-semibold">Account</h1>
    <GuidingLine />

    <EditableAvatar
      :pictureDataUri="profilePictureDataUri"
      :fallback="initials"
      :onChange="onChangeAvatar"
    />

    <EditableInput
      v-model:modelValue="email"
      title="Email"
      :isEmail="true"
      @update:modelValue="
        (value: string) => {
          onUpdateAccount({ newEmail: value })
          email = value
        }
      "
    />

    <EditableInput
      v-model:modelValue="fullName"
      title="Full name"
      :isEmail="false"
      @update:modelValue="
        (value: string) => {
          onUpdateAccount({ newFullName: value })
          fullName = value
        }
      "
    />

    <GuidingLine />

    <div class="w-full inline-flex items-center space-y-2 justify-between py-1">
      <div class="pr-8">
        <p class="text-sm">Two-factor authentication</p>
        <p class="text-xs text-muted-foreground text-gray-500">
          Select an extra layer of security by requiring a code when logging in.
        </p>
      </div>
      <Combobox v-model:currentOption="twoFactorAuthentication" :options="authentications" />
    </div>

    <!-- Biometric authentication -->
    <div class="w-full inline-flex items-center justify-between py-1">
      <div class="pr-8">
        <p class="text-sm">Biometric authentication</p>
        <p class="text-xs text-muted-foreground text-gray-500">
          Allow authentication via fingerprints or Face ID.
        </p>
      </div>
      <PreferenceSwitch
        :isChecked="biometricAuthentication"
        :onChange="updateBiometricAuthentication"
      />
    </div>
  </div>
</template>

// desktop-web-app/web-app/src/components/account/user-account.tsx
/*
 *  Copyright (c) 2025 TeamDev
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

import {Combobox} from "@/components/ui/common/combobox.tsx";
import {PreferenceSwitch} from "@/components/ui/common/preference-switch.tsx";
import {EditableAvatar} from "@/components/account/editable-avatar.tsx";
import {EditableInput} from "@/components/account/editable-input.tsx";
import {GuidingLine} from "@/components/ui/common/guiding-line.tsx";
import {useEffect, useState} from "react";
import {preferencesClient} from "@/rpc/preference-client.ts";
import {AccountSchema, ProfilePictureSchema} from "@/gen/preferences_pb.ts";
import {create} from "@bufbuild/protobuf";
import {imageToDataUri} from "@/converter/image.ts";
import {
    emailTwoFA,
    fromTfa,
    passkeyTwoFA,
    smsTwoFA,
    toTfa,
    TwoFAMethod
} from "@/converter/two-fa-method.ts";
import {preferencesStorage} from "@/storage/preferences-storage.ts";

/**
 * Available two-factor authentication methods.
 */
const authentications: TwoFAMethod[] = [
    emailTwoFA,
    smsTwoFA,
    passkeyTwoFA
];

/**
 * A component that allows managing the user's account.
 *
 * @constructor
 */
export function UserAccount() {
    const [profilePictureDataUri, setProfilePictureDataUri] = useState<string>("");
    const [fullName, setFullName] = useState<string>("");
    const [email, setEmail] = useState<string>("");
    const [twoFactorAuthentication, setTwoFactorAuthentication] =
        useState<TwoFAMethod>(preferencesStorage.twoFA());
    const [biometricAuthentication, setBiometricAuthentication] =
        useState<boolean>(preferencesStorage.biometricAuthenticationEnabled());

    useEffect(() => {
        (async () => {
            const account = await preferencesClient.getAccount({});
            setEmail(account.email);
            setFullName(account.fullName);

            const tfaMethod = fromTfa(account.twoFactorAuthentication);
            setTwoFactorAuthentication(tfaMethod);
            setBiometricAuthentication(account.biometricAuthentication);

            preferencesStorage.saveTwoFA(tfaMethod);
            preferencesStorage.saveBiometricAuthentication(account.biometricAuthentication);
            const profilePicture = await preferencesClient.getProfilePicture({});
            setProfilePictureDataUri(imageToDataUri(profilePicture.content));
        })();
    }, []);

    const onUpdateAccount = ({
                                 newFullName = fullName,
                                 newEmail = email,
                                 newTwoFactorAuthentication = twoFactorAuthentication,
                                 newBiometricAuthentication = biometricAuthentication
                             }: {
        newFullName?: string;
        newEmail?: string,
        newTwoFactorAuthentication?: TwoFAMethod,
        newBiometricAuthentication?: boolean
    }) => {
        const newAccount = create(AccountSchema, {
            fullName: newFullName,
            email: newEmail,
            twoFactorAuthentication: toTfa(newTwoFactorAuthentication),
            biometricAuthentication: newBiometricAuthentication
        });
        preferencesClient.setAccount(newAccount);
        preferencesStorage.saveTwoFA(newTwoFactorAuthentication);
        preferencesStorage.saveBiometricAuthentication(newBiometricAuthentication);
    };
    const onChangeAvatar = (file: File) => {
        const reader = new FileReader();
        reader.onload = () => {
            const newProfilePicture = create(ProfilePictureSchema, {
                content: new Uint8Array(reader.result as ArrayBuffer)
            });
            preferencesClient.setProfilePicture(newProfilePicture);
            setProfilePictureDataUri(imageToDataUri(newProfilePicture.content));
        };
        reader.readAsArrayBuffer(file);
    };
    return (
        <div className="space-y-4">
            <h1 className="text-2xl font-semibold">Account</h1>
            <GuidingLine/>
            <EditableAvatar onChange={onChangeAvatar} pictureDataUri={profilePictureDataUri}
                            fallback={fullName.split(" ").map(it => it[0]).join("")}/>
            <EditableInput title={"Email"} isEmail={true}
                           onChange={(value) => {
                               onUpdateAccount({newEmail: value});
                               setEmail(value);
                           }} value={email} id={"email"}/>
            <EditableInput title={"Full name"} isEmail={false} value={fullName}
                           onChange={(value) => {
                               onUpdateAccount({newFullName: value});
                               setFullName(value);
                           }} id={"fullname"}/>
            <GuidingLine/>
            <div className="w-full inline-flex items-center space-y-2 justify-between py-1">
                <div className="pr-8">
                    <p className="text-sm">Two-factor authentication</p>
                    <p className="text-xs text-muted-foreground text-gray-500">
                        Select an extra layer of security by requiring a code when logging in.
                    </p>
                </div>
                <Combobox onSelect={value => {
                    onUpdateAccount({newTwoFactorAuthentication: value as TwoFAMethod});
                    setTwoFactorAuthentication(value as TwoFAMethod);
                }} options={authentications}
                          currentOption={twoFactorAuthentication}/>
            </div>
            <div className="w-full inline-flex items-center justify-between py-1">
                <div className="pr-8">
                    <p className="text-sm">Biometric authentication</p>
                    <p className="text-xs text-muted-foreground text-gray-500">
                        Allow authentication via fingerprints or Face ID.
                    </p>
                </div>
                <PreferenceSwitch onChange={checked => {
                    onUpdateAccount({newBiometricAuthentication: checked});
                    setBiometricAuthentication(checked);
                }} isChecked={biometricAuthentication}/>
            </div>
        </div>
    );
}
